theme: jekyll-theme-cayman
url: https://andrewwise.co.uk
name: Andrew Wise
description: Web developer based in York
title: Andrew Wise
email: andrew@andrewwise.co.uk
instagram: https://www.instagram.com/_wisey_/
linkedin: https://www.linkedin.com/in/andrew-wise-b0b8942a/
exclude: ["CNAME", "README.md"]
locale: en_GB
author:
  name: Andrew Wise
  url: https://andrewwise.co.uk