theme: jekyll-theme-cayman
url: http://www.andrewwise.co.uk
name: Andrew Wise
description: Web developer based in York
title: Andrew Wise
email: andrew@andrewwise.co.uk
twitter:
  username: wisey1
  url: https://twitter.com/wisey1
linkedin: https://www.linkedin.com/in/andrew-wise-b0b8942a/
github:
  is_project_page: false
